---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: 329054710135.dkr.ecr.eu-west-1.amazonaws.com/demo
        ports:
        - containerPort: 80
